version: "2.1"
services:
  plex:
    image: jaymoulin/plex:1.25.2.5319-armhf
    container_name: plex
    expose:
      - 32400
      - 33400
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /home/pi/services/plex/library:/config
      - /home/pi/plexusb/Series:/tv
      - /home/pi/plexusb/Peliculas:/movies
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WHITELIST=*.*.*.*
    volumes:
      - /home/pi/services/transmission:/config
      - /home/pi/plexusb/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped